# Generated by Django 5.1.5 on 2025-02-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Distribuidora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "cnpj",
                    models.CharField(max_length=18, unique=True, verbose_name="CNPJ"),
                ),
                ("local", models.CharField(max_length=100, verbose_name="Local")),
            ],
        ),
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Preco"
            ),
        ),
    ]
